eng_extractor:
  voca_size: 66
  embedding_dim: 64
  num_filter: 128
  filter_size: 5

dna_extractor:
  voca_size: 4
  embedding_dim: 64
  num_filter: 128
  filter_size: 5

bilstm:
  # 125 is ok
  voca_size: 66
  n_class: 3
optimizer:
  name: "Adam"
  lr: 0.001

batch_size: 8
epochs: 2000
iters_per_epoch: 10
trade_off: 0.5
checkpoint_interval: 50